### ISSUE TITLE
How to automatically select top 50 coins by market cap and buy instead of having to confirm purchase a coin one by one each time? 

### ISSUE THREAD

**Issue by samestigoy** [johntitus/coinx#1]
Hi! First off, love the idea of buying the top 50 coins! Great idea! 

I'm not a techie guy and am having a bit of a difficult time trying to figure how when I want to make my weekly $100 buy, instead of having to type out each coin's symbol and buy each coin one by one and specifying yes to each transaction, is there a way where I can lump together a bunch of coins i want to buy and then specify to buy $2 of each? 

The latter way I feel like can save a lot of time.

**Comment by johntitus** [comment]
Not yet. In the future I hope to add a command like that, if there's enough interest in this tool.

**Comment by samestigoy** [comment]
Ah, I hope so too! I really like it! I already did my weeks worth 👍

**Comment by hasanakyol** [comment]
@johntitus this is awesome if you can add a single command:

coinx buy -t 50 -$ 2

-t is top 50 etc.

**Comment by braeckel** [comment]
I've not used this tool but if you are on Linux or Mac you should be able to use the 'yes' command on the command line to pipe in the required confirmation string an infinite number of times, each with a newline after it.  Windows may have something equivalent through PowerShell.  When coinx is done with its confirmations you can use Ctrl C to cancel out of the 'yes' command.

The argument to the "yes" command below ("Yes") is the string that will be repeated with a newline after it, if you leave this off the default is to use the string "y" instead.  See more info here: https://askubuntu.com/questions/71566/what-is-the-yes-command

yes Yes | coinx buy ...

**Comment by samestigoy** [comment]
@hasanakyol 👍 Something just like that.

**Comment by johntitus** [comment]
Implemented in 0.10.0.
