### ISSUE TITLE
Error: Cannot find module 'C:\index-config'

### ISSUE THREAD

**Issue by driftfox** [johntitus/coinx#13]
I just installed coinx and when trying to configure it with my API keys, I get the following error message:

```
C:\>coinx config poloniex
module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\index-config'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by driftfox** [comment]
I'm using `Windows 10 64-bit` with `node v8.0.0`

**Comment by johntitus** [comment]
Is coinx installed globally?

**Comment by driftfox** [comment]
Yes; I installed it globally. After opening this bug, I saw the comment from @jgfaust on issue #4 about renaming all coinx-*.js files to index-*.js in the root directory. I forked your project and gave that a shot. This fixed the problem in Windows, but when I tested it in Linux, I'm now getting an error message saying `coinx-config(1) does not exist, try --help`.

**Comment by johntitus** [comment]
Interesting. I don't have access to a Windows machine - would you mind trying something for me? 
- Change the files back to coinx-.js
- Rename index.js to coinx.js
- In package.json, change main to coinx.js, and change bin:coinx to './coinx.js'

Seems to work ok on linux, perhaps it will help on windows too?

**Comment by johntitus** [comment]
If that doesn't work, can you try changing package.json to use commander 2.6.0? Looks like the issue may be related.

**Comment by driftfox** [comment]
Renaming the index.js file seemed to work great. Thank you!
