### ISSUE TITLE
Is possible to find the price when i buyed some cryptocurrencies?

### ISSUE THREAD

**Issue by bohzio** [johntitus/coinx#2]
For example:
If I buyed 1 BTC in 2017-01-01 I would find how much I spent in this transaction.
This is for finding the percentage of earnings.

Thank you.

**Comment by samestigoy** [comment]
@mattia98tr Are you referring to the coin simulator he created? To find the price of bitcoin for instance on coinx you use: coinx price btc

**Comment by bohzio** [comment]
@samestigoy 
I mean that I would like to understand how much I earned. Coinx already has the functionality that tells me how much I have in my wallet but I would like to see how much I earned.
Thank you

**Comment by johntitus** [comment]
Coinx doesn't track your holdings. Sorry, just not what this is for.
