### ISSUE TITLE
What happens when there are no funds in your account?

### ISSUE THREAD

**Issue by nodox** [johntitus/coinx#28]
From the README, the script assumes you have funds in these exchanges to buy that many coins. How are you going about ensuring that funds are there for you to buy these coins? Is this script buying via fiat and then buying BTC which can be used to but the altcoin. Do you have any goals to add this to the roadmap if this is not part of the plan?

**Comment by johntitus** [comment]
If you try and buy and you don't have the necessary BTC, the exchange will return an error.  You have to buy the BTC yourself and get it to the exchange, this script doesn't deal with that.

**Comment by nodox** [comment]
Do you have any plans to add that functionality?

**Comment by johntitus** [comment]
I have no plans to add it.
