### ISSUE TITLE
Problem with setting up config to exchanges

### ISSUE THREAD

**Issue by KoningGeld** [johntitus/coinx#4]
Hi, 

I am new to cmd line programs but I would like to give this a try. I have the program running now, but when I try to run the config command it gives the following error.

> $ coinx config poloniex
> module.js:471
>     throw err;
>     ^
> 
> Error: Cannot find module 'C:\[pagthway to coinx-master folder here]\index-config'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:389:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:504:3

Would you be able to tell from this error what is going wrong? I am using Cygwin terminal on windows.

**Comment by jgfaust** [comment]
I'm not familiar enough with node to know the culprit, but it seems like the commander library expects each of the command scripts to be named the same as the "main" script, which is index.js.

The quickest solution but probably not the correct one is to rename each of the coinx-\*.js files to index-\*.js.  So, rename coinx-config.js to index-config.js.  Do the same for the rest of the coinx- files in the coinx root directory.

**Comment by KoningGeld** [comment]
thanks for the reply, I tried this but sadly no luck.

**Comment by KoningGeld** [comment]
Copied all the files into the folder of Cygwin instead of my own folder and now it works!
